
###################
### Auth Server ###
###################

[services.arbitrum-sepolia-auth-server]
[services.arbitrum-sepolia-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-arbitrum-sepolia"
cargo_features = "arbitrum"

[services.arbitrum-sepolia-auth-server.deploy]
environment = "arbitrum-sepolia"
resource = "auth-server"

[services.base-sepolia-auth-server]
[services.base-sepolia-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-base-sepolia"
cargo_features = "base"

[services.base-sepolia-auth-server.deploy]
environment = "base-sepolia"
resource = "auth-server"

[services.arbitrum-one-auth-server]
[services.arbitrum-one-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-arbitrum-one"
cargo_features = "arbitrum"

[services.arbitrum-one-auth-server.deploy]
environment = "arbitrum-one"
resource = "auth-server"

[services.base-mainnet-auth-server]
[services.base-mainnet-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-base-mainnet"
cargo_features = "base"

[services.base-mainnet-auth-server.deploy]
environment = "base-mainnet"
resource = "auth-server"

#####################
### Funds Manager ###
#####################

[services.testnet-funds-manager]
[services.testnet-funds-manager.build]
dockerfile = "funds-manager/Dockerfile"
ecr_repo = "funds-manager-testnet"

[services.testnet-funds-manager.deploy]
environment = "testnet"
resource = "funds-manager"

[services.mainnet-funds-manager]
[services.mainnet-funds-manager.build]
dockerfile = "funds-manager/Dockerfile"
ecr_repo = "funds-manager-mainnet"

[services.mainnet-funds-manager.deploy]
environment = "mainnet"
resource = "funds-manager"

#######################
### Renegade Solver ###
#######################

[services.base-mainnet-renegade-solver]
[services.base-mainnet-renegade-solver.build]
dockerfile = "renegade-solver/Dockerfile"
ecr_repo = "solver-base-mainnet"

[services.base-mainnet-renegade-solver.deploy]
environment = "base-mainnet"
resource = "solver"

#########################
### Compliance Server ###
#########################

[services.mainnet-compliance-server]
[services.mainnet-compliance-server.build]
dockerfile = "compliance/compliance-server/Dockerfile"
ecr_repo = "compliance-mainnet"

[services.mainnet-compliance-server.deploy]
environment = "mainnet"
resource = "compliance"

######################
### Price Reporter ### 
######################

[services.testnet-price-reporter]
[services.testnet-price-reporter.build]
dockerfile = "price-reporter/Dockerfile"
ecr_repo = "price-reporter-testnet"
region = "ca-central-1"

[services.testnet-price-reporter.deploy]
environment = "testnet"
resource = "price-reporter"
region = "ca-central-1"

[services.mainnet-price-reporter]
[services.mainnet-price-reporter.build]
dockerfile = "price-reporter/Dockerfile"
ecr_repo = "price-reporter-mainnet"
region = "ca-central-1"

[services.mainnet-price-reporter.deploy]
environment = "mainnet"
resource = "price-reporter"
region = "ca-central-1"

######################
### Prover Service ###
######################

[services.testnet-prover-service]
[services.testnet-prover-service.build]
dockerfile = "prover-service/Dockerfile"
ecr_repo = "prover-service-testnet-v2"
cargo_features = "log-invalid-bundles"

[services.testnet-prover-service.deploy]
environment = "testnet"
resource = "prover-service-v2"

[services.mainnet-prover-service]
[services.mainnet-prover-service.build]
dockerfile = "prover-service/Dockerfile"
ecr_repo = "prover-service-mainnet"
cargo_features = "log-invalid-bundles"

[services.mainnet-prover-service.deploy]
environment = "mainnet"
resource = "prover-service"
