[package]
name = "prover-service-api"
version = "0.1.0"
edition = "2024"

[dependencies]

# === Renegade Dependencies === #
renegade-circuits-core = { workspace = true }
renegade-circuit-types = { workspace = true }

# === Misc Dependencies === #
serde = { version = "1", features = ["derive"] }
