[package]
name = "darkpool-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
# === Renegade === #
renegade-constants = { package = "constants", path = "/Users/akirillo/code/renegade/constants" }
renegade-common = { package = "common", path = "/Users/akirillo/code/renegade/common" }
renegade-crypto = { path = "/Users/akirillo/code/renegade/renegade-crypto" }
renegade-circuit-types = { package = "circuit-types", path = "/Users/akirillo/code/renegade/circuit-types" }

# === Runtime === #
tokio = { version = "1.10", features = ["full"] }
clap = { version = "4.5.3", features = ["derive", "env"] }
futures-util = "0.3"

# === DB === #
diesel = { workspace = true, features = ["postgres", "numeric", "uuid"] }
diesel-async = { workspace = true, features = ["postgres", "deadpool"] }
native-tls = { workspace = true }
postgres-native-tls = { workspace = true }
tokio-postgres = { workspace = true }
bigdecimal = "0.4"
uuid = { version = "1.17.0", features = ["v4", "serde"] }

# === AWS === #
aws-config = { version = "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-sqs = "1.50.0"

# === API === #
darkpool-indexer-api = { path = "../darkpool-indexer-api" }
serde = "1.0"
serde_json = "1.0"

# === Blockchain === #
alloy = { workspace = true, features = ["provider-ws", "provider-trace-api", "provider-debug-api"] }
renegade-solidity-abi = { package = "abi", path = "/Users/akirillo/code/renegade-contracts/abi", features = ["v2"] }

# === Misc === #
thiserror = { workspace = true }
tracing = { workspace = true }
itertools = "0.10"

[dev-dependencies]
# === DB === #
postgresql_embedded = { version = "0.19", features = ["tokio", "bundled"] }
diesel_migrations = "2.3"
diesel-async = { workspace = true, features = ["migrations"] }

# === Blockchain === #
alloy = { workspace = true, features = ["getrandom"] }

# === Misc === #
rand = "0.8"
