[package]
name = "auth-server-api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = "1"
renegade-external-api = { workspace = true }
renegade-circuit-types = { workspace = true }
alloy-primitives = { version = "1.0.0" }
num-bigint = "0.4"
